### ISSUE TITLE
Ein Hyperlink funktioniert nicht mehr.

### ISSUE THREAD

**Issue by Daehdam** [programmieraffe/oerhoernchen#8]
Hallo liebes OERhörnchen,

auf dieser Seite (https://oerhoernchen.de/bildungsteiler/) funktioniert der Hyperlink (link geht auf: https://oerhoernchen.de/hochladen) bei der ersten Textzeile unter dem Titelbild leider nicht mehr.

"Lizenzhinweis erstellt - aber noch keine Ahnung, wo du Dein Bildungsmaterial veröffentlichen kannst? **Hier**(https://oerhoernchen.de/hochladen) gibt es Infos zum Veröffentlichen."

Liebe Grüße und beste Wünsche

**Comment by mandrasch** [comment]
Hi, danke für Meldung! Schau ich mir an. 👍  VG

**Comment by mandrasch** [comment]
Vielen Dank fürs Melden, habe die ursprüngliche Seite wiederhergestellt. 👍 VG
